"""Trusted fixed-reference solvers used by paired OptiProfiler evaluations."""

from __future__ import annotations

from pathlib import Path

from .config import EvaluationConfig
from .solver import InterfaceSpec, copy_initial_source


def materialize_reference(
    *,
    initial: Path,
    destination: Path,
    interface: InterfaceSpec,
    config: EvaluationConfig,
) -> Path:
    """Copy the initial solver or create a trusted built-in reference tree."""

    if config.reference == "initial":
        return copy_initial_source(initial, destination)
    if config.reference != "scipy_powell":
        raise ValueError(f"Unsupported evaluation reference: {config.reference!r}")

    factor = float(config.benchmark.get("max_eval_factor", 500))
    if factor <= 0:
        raise ValueError("benchmark.max_eval_factor must be positive.")
    entrypoint = destination / interface.file
    entrypoint.parent.mkdir(parents=True, exist_ok=False)
    entrypoint.write_text(_scipy_powell_source(interface.function, factor), encoding="utf-8")
    return destination


def _scipy_powell_source(function_name: str, max_eval_factor: float) -> str:
    return f'''"""Trusted SciPy Powell reference generated by OptiProfiler Evolve."""

import numpy as np
from scipy.optimize import minimize


def {function_name}(fun, x0):
    x0 = np.asarray(x0, dtype=float).reshape(-1)
    maxfev = max(1, int(np.ceil({max_eval_factor!r} * x0.size)))
    result = minimize(fun, x0, method="Powell", options={{"maxfev": maxfev}})
    return np.asarray(result.x, dtype=float)
'''


__all__: list[str] = []
